// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63675dd80c6c7bed8705c901
###
GET http://localhost:8080/contacts/63675dd80c6c7bed8705c902
###
GET http://localhost:8080/contacts/63675dd80c6c7bed8705c903

// PRODUCTION Deploy
###
GET https://cse341-rduw.onrender.com/contacts
###
GET https://cse341-rduw.onrender.com/contacts/63675dd80c6c7bed8705c901
###
GET https://cse341-rduw.onrender.com/contacts/63675dd80c6c7bed8705c902
###
GET https://cse341-rduw.onrender.com/contacts/63675dd80c6c7bed8705c903