// LOCALHOST
### request all data in collection
GET http://localhost:8080/contacts
### request a specific entry in database.
GET http://localhost:8080/contacts/636c8f4d038e0843c281b9af
### create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type:application/json

{
    "firstName":"Ashley", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com", 
    "favoriteColor":"Brown", 
    "birthday":"06/19/2000"
}
### edit contact 
PUT http://localhost:8080/contacts/636c8f4d038e0843c281b9af HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley 2", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com", 
    "favoriteColor":"Orange", 
    "birthday":"06/19/2000"
} 
### delete contact
DELETE http://localhost:8080/contacts/636c8f4d038e0843c281b9af HTTP/1.1
// PRODUCTION Deploy
###
GET https://cse341-rduw.onrender.com/contacts
###
GET https://cse341-rduw.onrender.com/contacts/636c8fc18f611e0fecf24fab
###
POST https://cse341-rduw.onrender.com/contacts HTTP/1.1
content-type:application/json

{
    "firstName":"Ashley", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com", 
    "favoriteColor":"Brown", 
    "birthday":"06/19/2000"
}
### edit conatact
PUT https://cse341-rduw.onrender.com/contacts/636c8fc18f611e0fecf24fab HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley 2", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com", 
    "favoriteColor":"orange", 
    "birthday":"06/19/2000"
} 
### delete contact
DELETE https://cse341-rduw.onrender.com/contacts/636c8fc18f611e0fecf24fab HTTP/1.1